(load-file (concat (file-name-directory load-file-name)
                   "lisp/core/load-paths.el"))

(require 'configure)
(configure/emacs-defaults)
(configure/text-editing)
(configure/auto-complete)
(configure/syntax-checking)
(configure/major-modes)
(configure/projects)

(add-hook 'find-file-not-found-hooks '(lambda ()
					(message "Dante: not file is found")
					(if (bound-and-true-p c++-mode)
					    (message "c++-mode is on")
					  (message "c++-mode is off"))))
