;; everfrost-common.el

;; https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces-for-Font-Lock.html
;; https://www.emacswiki.org/emacs/AddKeywords
(defun create-everfrost-theme (variant theme-name)

  (let ((class '((class color) (min-colors 89)))
	;; background
	(everfrost0 (if (eq variant 'dark) "#2b3339" "#fff9e8"))
	(everfrost1 (if (eq variant 'dark) "#323c41" "#f7f4e0"))
	(everfrost2 (if (eq variant 'dark) "#3a454a" "#f0eed9"))
	(everfrost3 (if (eq variant 'dark) "#445055" "#e9e8d2"))
	(everfrost4 (if (eq variant 'dark) "#4c555b" "#e1ddcb"))
	(everfrost5 (if (eq variant 'dark) "#53605c" "#bec5b2"))
	(everfrost6 (if (eq variant 'dark) "#503946" "#edf0cd"))
	(everfrost7 (if (eq variant 'dark) "#4e3e43" "#fce5dc"))
	(everfrost8 (if (eq variant 'dark) "#404d44" "#f1f3d4"))
	(everfrost9 (if (eq variant 'dark) "#394f5a" "#eaf2eb"))
	(everfrost10 (if (eq variant 'dark) "#4a4940" "#fbefd0"))

	;; foreground
	(everfrost-fg (if (eq variant 'dark) "#d3c6aa" "#5c6a72"))
	(everfrost-red (if (eq variant 'dark) "#e67e80" "#f85552"))
	(everfrost-orange (if (eq variant 'dark) "#e69875" "#f57d26"))
	(everfrost-yellow (if (eq variant 'dark) "#dbbc7f" "#dfa000"))
	(everfrost-green (if (eq variant 'dark) "#a7c080" "#8da101"))
	(everfrost-aqua (if (eq variant 'dark) "#83c092" "#35a77c"))
	(everfrost-blue (if (eq variant 'dark) "#7fbbb3" "#3a94c5"))
	(everfrost-purple (if (eq variant 'dark) "#d699b6" "#df69ba"))
	(everfrost-grey0 (if (eq variant 'dark) "#7a8478" "#a6b0a0"))
	(everfrost-grey1 (if (eq variant 'dark) "#859289" "#939f91"))
	(everfrost-grey2 (if (eq variant 'dark) "#9da9a0" "#829181"))
	(everfrost-cursor (if (eq variant 'dark) "#fff9e8" "#2b3339"))
	(everfrost-statusline1 (if (eq variant 'dark) "#a7c080" "#93b259"))
	(everfrost-statusline2 (if (eq variant 'dark) "#d3c6aa" "#708089"))
	(everfrost-statusline3 (if (eq variant 'dark) "#e67e80" "#e66868")))

    (custom-theme-set-faces
     theme-name
     `(bold ((,class (:weight bold))))
     `(bold-italic ((,class (:weight bold :slant italic))))
     `(default ((,class (:foreground ,everfrost-fg :background ,everfrost0))))
     `(error ((,class (:foreground ,everfrost-statusline3 :weight bold))))
     `(escape-glyph ((,class (:foreground ,everfrost10))))
     `(font-lock-builtin-face ((,class (:foreground ,everfrost-aqua))))
     `(font-lock-comment-face ((,class (:foreground ,everfrost-grey1))))
     `(font-lock-comment-delimiter-face ((,class (:foreground ,everfrost-grey1))))
     `(font-lock-constant-face ((,class (:foreground ,everfrost-purple))))
     `(font-lock-doc-face ((,class (:foreground ,everfrost5))))
     `(font-lock-function-name-face ((,class (:foreground ,everfrost-green))))
     `(font-lock-keyword-face ((,class (:foreground ,everfrost-red))))
     `(font-lock-negation-char-face ((,class (:foreground ,everfrost9))))
     `(font-lock-preprocessor-face ((,class (:foreground ,everfrost-purple :weight bold))))
     `(font-lock-reference-face ((,class (:foreground ,everfrost9))))
     ;;`(font-lock-regexp-grouping-backslash ((,class (:foreground ,everfrost13))))
     ;;`(font-lock-regexp-grouping-construct ((,class (:foreground ,everfrost13))))
     `(font-lock-string-face ((,class (:foreground ,everfrost-aqua))))
     `(font-lock-type-face ((,class (:foreground ,everfrost-yellow))))
     `(font-lock-variable-name-face ((,class (:foreground ,everfrost-fg))))
     `(font-lock-warning-face ((,class (:foreground ,everfrost-orange))))
     `(italic ((,class (:slant italic))))
     `(shadow ((,class (:foreground ,everfrost3))))
     `(underline ((,class (:underline t))))
     `(warning ((,class (:foreground ,everfrost-orange :weight bold))))

     ;; +--- Syntax ---+
     ;; > C
     ;; `(c-annotation-face ((,class (:foreground ,everfrost-annotation))))
     ;; 
     ;;  ;; > diff
     ;;  `(diff-added ((,class (:foreground ,everfrost14))))
     ;;  `(diff-changed ((,class (:foreground ,everfrost13))))
     ;;  `(diff-context ((,class (:inherit default))))
     ;;  `(diff-file-header ((,class (:foreground ,everfrost8))))
     ;;  `(diff-function ((,class (:foreground ,everfrost7))))
     ;;  `(diff-header ((,class (:foreground ,everfrost9 :weight bold))))
     ;;  `(diff-hunk-header ((,class (:foreground ,everfrost9 :background ,everfrost0))))
     ;;  `(diff-indicator-added ((,class (:foreground ,everfrost14))))
     ;;  `(diff-indicator-changed ((,class (:foreground ,everfrost13))))
     ;;  `(diff-indicator-removed ((,class (:foreground ,everfrost11))))
     ;;  `(diff-nonexistent ((,class (:foreground ,everfrost11))))
     ;;  `(diff-refine-added ((,class (:foreground ,everfrost14))))
     ;;  `(diff-refine-changed ((,class (:foreground ,everfrost13))))
     ;;  `(diff-refine-removed ((,class (:foreground ,everfrost11))))
     ;;  `(diff-removed ((,class (:foreground ,everfrost11))))
     ;; 
     ;; +--- UI ---+
     `(border ((,class (:foreground ,everfrost4))))
     `(buffer-menu-buffer ((,class (:foreground ,everfrost-fg :weight bold))))
     ;;  `(button ((,class (:background ,everfrost0 :foreground ,everfrost8 :box (:line-width 2 :color ,everfrost4 :style sunken-button)))))
     `(completions-annotations ((,class (:foreground ,everfrost9))))
     ;;  `(completions-common-part ((,class (:foreground ,everfrost8 :weight bold))))
     ;;  `(completions-first-difference ((,class (:foreground ,everfrost11))))
     ;;  `(custom-button ((,class (:background ,everfrost0 :foreground ,everfrost8 :box (:line-width 2 :color ,everfrost4 :style sunken-button)))))
     ;;  `(custom-button-mouse ((,class (:background ,everfrost4 :foreground ,everfrost0 :box (:line-width 2 :color ,everfrost4 :style sunken-button)))))
     ;;  `(custom-button-pressed ((,class (:background ,everfrost6 :foreground ,everfrost0 :box (:line-width 2 :color ,everfrost4 :style sunken-button)))))
     ;;  `(custom-button-pressed-unraised ((,class (:background ,everfrost4 :foreground ,everfrost0 :box (:line-width 2 :color ,everfrost4 :style sunken-button)))))
     ;;  `(custom-button-unraised ((,class (:background ,everfrost0 :foreground ,everfrost8 :box (:line-width 2 :color ,everfrost4 :style sunken-button)))))
     ;;  `(custom-changed ((,class (:foreground ,everfrost13))))
     ;;  `(custom-comment ((,class (:foreground ,everfrost-comment))))
     ;;  `(custom-comment-tag ((,class (:foreground ,everfrost7))))
     ;;  `(custom-documentation ((,class (:foreground ,everfrost4))))
     ;;  `(custom-group-tag ((,class (:foreground ,everfrost8 :weight bold))))
     ;;  `(custom-group-tag-1 ((,class (:foreground ,everfrost8 :weight bold))))
     ;;  `(custom-invalid ((,class (:foreground ,everfrost11))))
     ;;  `(custom-modified ((,class (:foreground ,everfrost13))))
     ;;  `(custom-rogue ((,class (:foreground ,everfrost12 :background ,everfrost2))))
     ;;  `(custom-saved ((,class (:foreground ,everfrost14))))
     ;;  `(custom-set ((,class (:foreground ,everfrost8))))
     ;;  `(custom-state ((,class (:foreground ,everfrost14))))
     ;;  `(custom-themed ((,class (:foreground ,everfrost8 :background ,everfrost2))))
     `(cursor ((,class (:background ,everfrost-cursor))))
     `(fringe ((,class (:foreground ,everfrost4 :background ,everfrost0))))
     `(file-name-shadow ((,class (:inherit shadow))))
     `(header-line ((,class (:foreground ,everfrost-green :background ,everfrost-aqua))))
     `(help-argument-name ((,class (:foreground ,everfrost8))))
     `(highlight ((,class (:foreground ,everfrost-statusline2 :background ,everfrost7))))
     `(hl-line ((,class (:background ,everfrost-red))))
     `(info-menu-star ((,class (:foreground ,everfrost7))))
     `(isearch ((,class (:foreground ,everfrost0 :background ,everfrost8))))
     `(isearch-fail ((,class (:foreground ,everfrost-red))))
     ;;  `(link ((,class (:underline t))))
     ;;  `(link-visited ((,class (:underline t))))
     ;;  `(linum ((,class (:foreground ,everfrost3 :background ,everfrost0))))
     ;;  `(linum-relative-current-face ((,class (:foreground ,everfrost3 :background ,everfrost0))))
     `(match ((,class (:inherit isearch))))
     ;;  `(message-cited-text ((,class (:foreground ,everfrost4))))
     `(message-header-cc ((,class (:foreground ,everfrost-fg))))
     ;;  `(message-header-name ((,class (:foreground ,everfrost7))))
     ;;  `(message-header-newsgroup ((,class (:foreground ,everfrost14))))
     ;;  `(message-header-other ((,class (:foreground ,everfrost4))))
     ;;  `(message-header-subject ((,class (:foreground ,everfrost8))))
     `(message-header-to ((,class (:foreground ,everfrost-fg))))
     ;;  `(message-header-xheader ((,class (:foreground ,everfrost13))))
     ;;  `(message-mml ((,class (:foreground ,everfrost10))))
     ;;  `(message-separator ((,class (:inherit shadow))))
     `(minibuffer-prompt ((,class (:foreground ,everfrost-blue :weight bold))))
     `(mm-command-output ((,class (:foreground ,everfrost-fg))))
     `(mode-line ((,class (:foreground ,everfrost-statusline2 :background ,everfrost4))))
     `(mode-line-buffer-id ((,class (:weight bold))))
     `(mode-line-highlight ((,class (:inherit highlight))))
     `(mode-line-inactive ((,class (:foreground ,everfrost2))))
     `(next-error ((,class (:inherit error))))
     `(nobreak-space ((,class (:foreground ,everfrost3))))
     `(outline-1 ((,class (:foreground ,everfrost8 :weight bold))))
     `(outline-2 ((,class (:inherit outline-1))))
     `(outline-3 ((,class (:inherit outline-1))))
     `(outline-4 ((,class (:inherit outline-1))))
     `(outline-5 ((,class (:inherit outline-1))))
     `(outline-6 ((,class (:inherit outline-1))))
     `(outline-7 ((,class (:inherit outline-1))))
     `(outline-8 ((,class (:inherit outline-1))))
     ;;  `(package-description ((,class (:foreground ,everfrost4))))
     ;;  `(package-help-section-name ((,class (:foreground ,everfrost8 :weight bold))))
     ;;  `(package-name ((,class (:foreground ,everfrost8))))
     ;;  `(package-status-available ((,class (:foreground ,everfrost7))))
     ;;  `(package-status-avail-obso ((,class (:foreground ,everfrost7 :slant italic))))
     ;;  `(package-status-built-in ((,class (:foreground ,everfrost9))))
     ;;  `(package-status-dependency ((,class (:foreground ,everfrost8 :slant italic))))
     ;;  `(package-status-disabled ((,class (:foreground ,everfrost3))))
     ;;  `(package-status-external ((,class (:foreground ,everfrost12 :slant italic))))
     ;;  `(package-status-held ((,class (:foreground ,everfrost4 :weight bold))))
     ;;  `(package-status-new ((,class (:foreground ,everfrost14))))
     ;;  `(package-status-incompat ((,class (:foreground ,everfrost11))))
     ;;  `(package-status-installed ((,class (:foreground ,everfrost7 :weight bold))))
     ;;  `(package-status-unsigned ((,class (:underline ,everfrost13))))
     ;;  `(query-replace ((,class (:foreground ,everfrost8 :background ,everfrost2))))
     `(region ((,class (:background ,everfrost6))))
     ;;  `(scroll-bar ((,class (:background ,everfrost3))))
     ;;  `(secondary-selection ((,class (:background ,everfrost2))))
     ;; 
     ;;  ;; `show-paren-match-face` and `show-paren-mismatch-face` are deprecated since Emacs version 22.1 and were
     ;;  ;; removed in Emacs 25.
     ;;  ;; https://github.com/arcticicestudio/everfrost-emacs/issues/75
     ;;  ;; http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=c430f7e23fc2c22f251ace4254e37dea1452dfc3
     ;;  ;; https://github.com/emacs-mirror/emacs/commit/c430f7e23fc2c22f251ace4254e37dea1452dfc3
     ;;  `(show-paren-match-face ((,class (:foreground ,everfrost0 :background ,everfrost8))))
     ;;  `(show-paren-mismatch-face ((,class (:background ,everfrost11))))
     ;; 
     ;;  `(show-paren-match ((,class (:foreground ,everfrost0 :background ,everfrost8))))
     ;;  `(show-paren-mismatch ((,class (:background ,everfrost11))))
     `(success ((,class (:foreground ,everfrost-statusline1))))
     ;;  `(term ((,class (:foreground ,everfrost4 :background ,everfrost0))))
     ;;  `(term-color-black ((,class (:foreground ,everfrost1 :background ,everfrost1))))
     ;;  `(term-color-white ((,class (:foreground ,everfrost5 :background ,everfrost5))))
     ;;  `(term-color-cyan ((,class (:foreground ,everfrost7 :background ,everfrost7))))
     ;;  `(term-color-blue ((,class (:foreground ,everfrost8 :background ,everfrost8))))
     ;;  `(term-color-red ((,class (:foreground ,everfrost11 :background ,everfrost11))))
     ;;  `(term-color-yellow ((,class (:foreground ,everfrost13 :background ,everfrost13))))
     ;;  `(term-color-green ((,class (:foreground ,everfrost14 :background ,everfrost14))))
     ;;  `(term-color-magenta ((,class (:foreground ,everfrost15 :background ,everfrost15))))
     ;;  `(tool-bar ((,class (:foreground ,everfrost4 :background ,everfrost3))))
     ;;  `(tooltip ((,class (:foreground ,everfrost0 :background ,everfrost4))))
     `(trailing-whitespace ((,class (:foreground ,everfrost-aqua))))
     ;;  `(tty-menu-disabled-face ((,class (:foreground ,everfrost1))))
     ;;  `(tty-menu-enabled-face ((,class (:background ,everfrost2 foreground ,everfrost4))))
     `(tty-menu-selected-face ((,class (:foreground ,everfrost-purple :underline t))))
     ;;  `(undo-tree-visualizer-current-face ((,class (:foreground ,everfrost8))))
     ;;  `(undo-tree-visualizer-default-face ((,class (:foreground ,everfrost4))))
     ;;  `(undo-tree-visualizer-unmodified-face ((,class (:foreground ,everfrost4))))
     ;;  `(undo-tree-visualizer-register-face ((,class (:foreground ,everfrost9))))
     ;;  `(vc-conflict-state ((,class (:foreground ,everfrost12))))
     ;;  `(vc-edited-state ((,class (:foreground ,everfrost13))))
     ;;  `(vc-locally-added-state ((,class (:underline ,everfrost14))))
     ;;  `(vc-locked-state ((,class (:foreground ,everfrost10))))
     ;;  `(vc-missing-state ((,class (:foreground ,everfrost11))))
     ;;  `(vc-needs-update-state ((,class (:foreground ,everfrost12))))
     ;;  `(vc-removed-state ((,class (:foreground ,everfrost11))))
     ;;  `(vc-state-base ((,class (:foreground ,everfrost4))))
     ;;  `(vc-up-to-date-state ((,class (:foreground ,everfrost8))))
     ;;  `(vertical-border ((,class (:foreground ,everfrost2))))
     ;;  `(which-func ((,class (:foreground ,everfrost8))))
     `(whitespace-big-indent ((,class (:foreground ,everfrost-aqua :background ,everfrost0))))
     `(whitespace-empty ((,class (:foreground ,everfrost-aqua :background ,everfrost0))))
     `(whitespace-hspace ((,class (:foreground ,everfrost-aqua :background ,everfrost0))))
     `(whitespace-indentation ((,class (:foreground ,everfrost-aqua :background ,everfrost0))))
     `(whitespace-line ((,class (:background ,everfrost-aqua))))
     `(whitespace-newline ((,class (:foreground ,everfrost-aqua :background ,everfrost0))))
     `(whitespace-space ((,class (:foreground ,everfrost-aqua :background ,everfrost0))))
     `(whitespace-space-after-tab ((,class (:foreground ,everfrost-aqua :background ,everfrost0))))
     `(whitespace-space-before-tab ((,class (:foreground ,everfrost-aqua :background ,everfrost0))))
     `(whitespace-tab ((,class (:foreground ,everfrost3 :background ,everfrost0))))
     `(whitespace-trailing ((,class (:inherit trailing-whitespace))))
     ;;  `(widget-button-pressed ((,class (:foreground ,everfrost9 :background ,everfrost1))))
     ;;  `(widget-documentation ((,class (:foreground ,everfrost4))))
     ;;  `(widget-field ((,class (:background ,everfrost2 :foreground ,everfrost4))))
     ;;  `(widget-single-line-field ((,class (:background ,everfrost2 :foreground ,everfrost4))))
     ;;  `(window-divider ((,class (:background ,everfrost3))))
     ;;  `(window-divider-first-pixel ((,class (:background ,everfrost3))))
     ;;  `(window-divider-last-pixel ((,class (:background ,everfrost3))))
     ;; 
     ;; ;;;; +-----------------+
     ;; ;;;; + Package Support +
     ;; ;;;; +-----------------+
     ;;  ;; +--- Syntax ---+
     ;;  ;; > JavaScript 2
     ;;  `(js2-function-call ((,class (:foreground ,everfrost8))))
     ;;  `(js2-private-function-call ((,class (:foreground ,everfrost8))))
     ;;  `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,everfrost6))))
     ;;  `(js2-jsdoc-html-tag-name ((,class (:foreground ,everfrost9))))
     ;;  `(js2-external-variable ((,class (:foreground ,everfrost4))))
     ;;  `(js2-function-param ((,class (:foreground ,everfrost4))))
     ;;  `(js2-jsdoc-value ((,class (:foreground ,everfrost-comment))))
     ;;  `(js2-jsdoc-tag ((,class (:foreground ,everfrost7))))
     ;;  `(js2-jsdoc-type ((,class (:foreground ,everfrost7))))
     ;;  `(js2-private-member ((,class (:foreground ,everfrost4))))
     ;;  `(js2-object-property ((,class (:foreground ,everfrost4))))
     ;;  `(js2-error ((,class (:foreground ,everfrost11))))
     ;;  `(js2-warning ((,class (:foreground ,everfrost13))))
     ;;  `(js2-instance-member ((,class (:foreground ,everfrost4))))
     ;; 
     ;;  ;; > JavaScript 3
     ;;  `(js3-error-face ((,class (:foreground ,everfrost11))))
     ;;  `(js3-external-variable-face ((,class (:foreground ,everfrost4))))
     ;;  `(js3-function-param-face ((,class (:foreground ,everfrost4))))
     ;;  `(js3-instance-member-face ((,class (:foreground ,everfrost4))))
     ;;  `(js3-jsdoc-html-tag-delimiter-face ((,class (:foreground ,everfrost6))))
     ;;  `(js3-jsdoc-html-tag-name-face ((,class (:foreground ,everfrost9))))
     ;;  `(js3-jsdoc-tag-face ((,class (:foreground ,everfrost9))))
     ;;  `(js3-jsdoc-type-face ((,class (:foreground ,everfrost7))))
     ;;  `(js3-jsdoc-value-face ((,class (:foreground ,everfrost4))))
     ;;  `(js3-magic-paren-face ((,class (:inherit show-paren-match-face))))
     ;;  `(js3-private-function-call-face ((,class (:foreground ,everfrost8))))
     ;;  `(js3-private-member-face ((,class (:foreground ,everfrost4))))
     ;;  `(js3-warning-face ((,class (:foreground ,everfrost13))))
     ;; 
     ;;  ;; > Markdown
     ;;  `(markdown-blockquote-face ((,class (:foreground ,everfrost-comment))))
     ;;  `(markdown-bold-face ((,class (:inherit bold))))
     ;;  `(markdown-header-face-1 ((,class (:foreground ,everfrost8))))
     ;;  `(markdown-header-face-2 ((,class (:foreground ,everfrost8))))
     ;;  `(markdown-header-face-3 ((,class (:foreground ,everfrost8))))
     ;;  `(markdown-header-face-4 ((,class (:foreground ,everfrost8))))
     ;;  `(markdown-header-face-5 ((,class (:foreground ,everfrost8))))
     ;;  `(markdown-header-face-6 ((,class (:foreground ,everfrost8))))
     ;;  `(markdown-inline-code-face ((,class (:foreground ,everfrost7))))
     ;;  `(markdown-italic-face ((,class (:inherit italic))))
     ;;  `(markdown-link-face ((,class (:foreground ,everfrost8))))
     ;;  `(markdown-markup-face ((,class (:foreground ,everfrost9))))
     ;;  `(markdown-reference-face ((,class (:inherit markdown-link-face))))
     ;;  `(markdown-url-face ((,class (:foreground ,everfrost4 :underline t))))
     ;; 
     ;;  ;; > Rainbow Delimeters
     ;;  `(rainbow-delimiters-depth-1-face ((,class :foreground ,everfrost7)))
     ;;  `(rainbow-delimiters-depth-2-face ((,class :foreground ,everfrost8)))
     ;;  `(rainbow-delimiters-depth-3-face ((,class :foreground ,everfrost9)))
     ;;  `(rainbow-delimiters-depth-4-face ((,class :foreground ,everfrost10)))
     ;;  `(rainbow-delimiters-depth-5-face ((,class :foreground ,everfrost12)))
     ;;  `(rainbow-delimiters-depth-6-face ((,class :foreground ,everfrost13)))
     ;;  `(rainbow-delimiters-depth-7-face ((,class :foreground ,everfrost14)))
     ;;  `(rainbow-delimiters-depth-8-face ((,class :foreground ,everfrost15)))
     ;;  `(rainbow-delimiters-unmatched-face ((,class :foreground ,everfrost11)))
     ;; 
     ;;  ;; > Web Mode
     ;;  `(web-mode-attr-tag-custom-face ((,class (:foreground ,everfrost-attribute))))
     ;;  `(web-mode-builtin-face ((,class (:foreground ,everfrost-keyword))))
     ;;  `(web-mode-comment-face ((,class (:foreground ,everfrost-comment))))
     ;;  `(web-mode-comment-keyword-face ((,class (:foreground ,everfrost-comment))))
     ;;  `(web-mode-constant-face ((,class (:foreground ,everfrost-variable))))
     ;;  `(web-mode-css-at-rule-face ((,class (:foreground ,everfrost-annotation))))
     ;;  `(web-mode-css-function-face ((,class (:foreground ,everfrost-method))))
     ;;  `(web-mode-css-property-name-face ((,class (:foreground ,everfrost-keyword))))
     ;;  `(web-mode-css-pseudo-class-face ((,class (:foreground ,everfrost-class))))
     ;;  `(web-mode-css-selector-face ((,class (:foreground ,everfrost-keyword))))
     ;;  `(web-mode-css-string-face ((,class (:foreground ,everfrost-string))))
     ;;  `(web-mode-doctype-face ((,class (:foreground ,everfrost-preprocessor))))
     ;;  `(web-mode-function-call-face ((,class (:foreground ,everfrost-method))))
     ;;  `(web-mode-function-name-face ((,class (:foreground ,everfrost-method))))
     ;;  `(web-mode-html-attr-name-face ((,class (:foreground ,everfrost-attribute))))
     ;;  `(web-mode-html-attr-equal-face ((,class (:foreground ,everfrost-punctuation))))
     ;;  `(web-mode-html-attr-value-face ((,class (:foreground ,everfrost-string))))
     ;;  `(web-mode-html-entity-face ((,class (:foreground ,everfrost-keyword))))
     ;;  `(web-mode-html-tag-bracket-face ((,class (:foreground ,everfrost-punctuation))))
     ;;  `(web-mode-html-tag-custom-face ((,class (:foreground ,everfrost-tag))))
     ;;  `(web-mode-html-tag-face ((,class (:foreground ,everfrost-tag))))
     ;;  `(web-mode-html-tag-namespaced-face ((,class (:foreground ,everfrost-keyword))))
     ;;  `(web-mode-json-key-face ((,class (:foreground ,everfrost-class))))
     ;;  `(web-mode-json-string-face ((,class (:foreground ,everfrost-string))))
     ;;  `(web-mode-keyword-face ((,class (:foreground ,everfrost-keyword))))
     ;;  `(web-mode-preprocessor-face ((,class (:foreground ,everfrost-preprocessor))))
     ;;  `(web-mode-string-face ((,class (:foreground ,everfrost-string))))
     ;;  `(web-mode-symbol-face ((,class (:foreground ,everfrost-variable))))
     ;;  `(web-mode-type-face ((,class (:foreground ,everfrost-class))))
     ;;  `(web-mode-warning-face ((,class (:inherit ,font-lock-warning-face))))
     ;;  `(web-mode-variable-name-face ((,class (:foreground ,everfrost-variable))))
     ;; 
     ;;  ;; +--- UI ---+
     ;;  ;; > Anzu
     ;;  `(anzu-mode-line ((,class (:foreground, everfrost8))))
     ;;  `(anzu-mode-line-no-match ((,class (:foreground, everfrost11))))
     ;; 
     ;;  ;; > Avy
     ;;  `(avy-lead-face ((,class (:background ,everfrost11 :foreground ,everfrost5))))
     ;;  `(avy-lead-face-0 ((,class (:background ,everfrost10 :foreground ,everfrost5))))
     ;;  `(avy-lead-face-1 ((,class (:background ,everfrost3 :foreground ,everfrost5))))
     ;;  `(avy-lead-face-2 ((,class (:background ,everfrost15 :foreground ,everfrost5))))
     ;; 
     ;;  ;; > Company
     `(company-echo-common ((,class (:foreground ,everfrost0 :background ,everfrost4))))
     `(company-preview ((,class (:foreground ,everfrost4 :background ,everfrost10))))
     `(company-preview-common ((,class (:foreground ,everfrost0 :background ,everfrost8))))
     `(company-preview-search ((,class (:foreground ,everfrost0 :background ,everfrost8))))
     `(company-scrollbar-bg ((,class (:foreground ,everfrost1 :background ,everfrost1))))
     `(company-scrollbar-fg ((,class (:foreground ,everfrost2 :background ,everfrost2))))
     `(company-template-field ((,class (:foreground ,everfrost0 :background ,everfrost7))))
     `(company-tooltip ((,class (:foreground ,everfrost-fg :background ,everfrost3))))
     `(company-tooltip-annotation ((,class (:foreground ,everfrost-aqua))))
     `(company-tooltip-annotation-selection ((,class (:foreground ,everfrost9 :weight bold))))
     `(company-tooltip-common ((,class (:foreground ,everfrost-fg))))
     `(company-tooltip-common-selection ((,class (:foreground ,everfrost10 :background ,everfrost-statusline1))))
     `(company-tooltip-selection ((,class (:background ,everfrost-statusline1 :foreground ,everfrost10 :weight bold))))

     ;; > diff-hl
     `(diff-hl-change ((,class (:background ,everfrost-purple))))
     `(diff-hl-insert ((,class (:background ,everfrost-statusline1))))
     `(diff-hl-delete ((,class (:background ,everfrost-statusline3))))

     ;; > Flycheck
     `(flycheck-error ((,class (:underline (:style wave :color ,everfrost-statusline3)))))
     `(flycheck-fringe-error ((,class (:foreground ,everfrost-statusline3 :weight bold))))
     `(flycheck-fringe-info ((,class (:foreground ,everfrost-blue :weight bold))))
     `(flycheck-fringe-warning ((,class (:foreground ,everfrost-yellow :weight bold))))
     `(flycheck-info ((,class (:underline (:style wave :color ,everfrost-blue)))))
     `(flycheck-warning ((,class (:underline (:style wave :color ,everfrost-yellow)))))

     ;; > Git Gutter
     `(git-gutter:modified ((,class (:foreground ,everfrost-purple))))
     `(git-gutter:added ((,class (:foreground ,everfrost-statusline1))))
     `(git-gutter:deleted ((,class (:foreground ,everfrost-statusline3))))

     ;; > Git Gutter Plus
     `(git-gutter+-modified ((,class (:foreground ,everfrost-purple))))
     `(git-gutter+-added ((,class (:foreground ,everfrost-statusline1))))
     `(git-gutter+-deleted ((,class (:foreground ,everfrost-statusline3))))

     ;;  ;; > Magit
     ;;  `(magit-branch ((,class (:foreground ,everfrost7 :weight bold))))
     ;;  `(magit-diff-context-highlight ((,class (:background ,everfrost2))))
     ;;  `(magit-diff-file-header ((,class (:foreground ,everfrost8 :box (:color ,everfrost8)))))
     ;;  `(magit-diffstat-added ((,class (:foreground ,everfrost14))))
     ;;  `(magit-diffstat-removed ((,class (:foreground ,everfrost11))))
     ;;  `(magit-hash ((,class (:foreground ,everfrost8))))
     ;;  `(magit-hunk-heading ((,class (:foreground ,everfrost9))))
     ;;  `(magit-hunk-heading-highlight ((,class (:foreground ,everfrost9 :background ,everfrost2))))
     ;;  `(magit-item-highlight ((,class (:foreground ,everfrost8 :background ,everfrost2))))
     ;;  `(magit-log-author ((,class (:foreground ,everfrost7))))
     ;;  `(magit-process-ng ((,class (:foreground ,everfrost13 :weight bold))))
     ;;  `(magit-process-ok ((,class (:foreground ,everfrost14 :weight bold))))
     ;;  `(magit-section-heading ((,class (:foreground ,everfrost7 :weight bold))))
     ;;  `(magit-section-highlight ((,class (:background ,everfrost2))))
     ;; 
     ;;  ;; > MU4E
     ;;  `(mu4e-header-marks-face ((,class (:foreground ,everfrost9))))
     ;;  `(mu4e-title-face ((,class (:foreground ,everfrost8))))
     ;;  `(mu4e-header-key-face ((,class (:foreground ,everfrost8))))
     ;;  `(mu4e-highlight-face ((,class (:highlight))))
     ;;  `(mu4e-flagged-face ((,class (:foreground ,everfrost13))))
     ;;  `(mu4e-unread-face ((,class (:foreground ,everfrost13 :weight bold))))
     ;;  `(mu4e-link-face ((,class (:underline t))))
     ;; 
     ;;  ;; > Powerline
     ;;  `(powerline-active1 ((,class (:foreground ,everfrost4 :background ,everfrost1))))
     ;;  `(powerline-active2 ((,class (:foreground ,everfrost4 :background ,everfrost3))))
     ;;  `(powerline-inactive1 ((,class (:background ,everfrost2))))
     ;;  `(powerline-inactive2 ((,class (:background ,everfrost2))))
     ;; 
     ;;  ;; > Powerline Evil
     ;;  `(powerline-evil-base-face ((,class (:foreground ,everfrost4))))
     ;;  `(powerline-evil-normal-face ((,class (:background ,everfrost8))))
     ;;  `(powerline-evil-insert-face ((,class (:foreground ,everfrost0 :background ,everfrost4))))
     ;;  `(powerline-evil-visual-face ((,class (:foreground ,everfrost0 :background ,everfrost7))))
     ;;  `(powerline-evil-replace-face ((,class (:foreground ,everfrost0 :background ,everfrost9))))
     ;; 
     ;;  ;; > Cider
     ;;  `(cider-result-overlay-face ((t (:background unspecified))))
     ;; 
     ;;  ;; > Org
     ;;  `(org-level-1 ((,class (:foreground ,everfrost7 :weight extra-bold))))
     ;;  `(org-level-2 ((,class (:foreground ,everfrost8 :weight bold))))
     ;;  `(org-level-3 ((,class (:foreground ,everfrost9 :weight semi-bold))))
     ;;  `(org-level-4 ((,class (:foreground ,everfrost10 :weight normal))))
     ;;  `(org-level-5 ((,class (:inherit org-level-4))))
     ;;  `(org-level-6 ((,class (:inherit org-level-4))))
     ;;  `(org-level-7 ((,class (:inherit org-level-4))))
     ;;  `(org-level-8 ((,class (:inherit org-level-4))))
     ;;  `(org-agenda-structure ((,class (:foreground ,everfrost9))))
     ;;  `(org-agenda-date ((,class (:foreground ,everfrost8 :underline nil))))
     ;;  `(org-agenda-done ((,class (:foreground ,everfrost14))))
     ;;  `(org-agenda-dimmed-todo-face ((,class (:background ,everfrost13))))
     ;;  `(org-block ((,class (:foreground ,everfrost4))))
     ;;  `(org-block-background ((,class (:background ,everfrost0))))
     ;;  `(org-block-begin-line ((,class (:foreground ,everfrost7))))
     ;;  `(org-block-end-line ((,class (:foreground ,everfrost7))))
     ;;  `(org-checkbox ((,class (:foreground ,everfrost9))))
     ;;  `(org-checkbox-statistics-done ((,class (:foreground ,everfrost14))))
     ;;  `(org-checkbox-statistics-todo ((,class (:foreground ,everfrost13))))
     ;;  `(org-code ((,class (:foreground ,everfrost7))))
     ;;  `(org-column ((,class (:background ,everfrost2))))
     ;;  `(org-column-title ((,class (:inherit org-column :weight bold :underline t))))
     ;;  `(org-date ((,class (:foreground ,everfrost8))))
     ;;  `(org-document-info ((,class (:foreground ,everfrost4))))
     ;;  `(org-document-info-keyword ((,class (:foreground ,everfrost3 :weight bold))))
     ;;  `(org-document-title ((,class (:foreground ,everfrost8 :weight bold))))
     ;;  `(org-done ((,class (:foreground ,everfrost14 :weight bold))))
     ;;  `(org-ellipsis ((,class (:foreground ,everfrost3))))
     ;;  `(org-footnote ((,class (:foreground ,everfrost8))))
     ;;  `(org-formula ((,class (:foreground ,everfrost9))))
     ;;  `(org-hide ((,class (:foreground ,everfrost0 :background ,everfrost0))))
     ;;  `(org-link ((,class (:underline t))))
     ;;  `(org-scheduled ((,class (:foreground ,everfrost14))))
     ;;  `(org-scheduled-previously ((,class (:foreground ,everfrost13))))
     ;;  `(org-scheduled-today ((,class (:foreground ,everfrost8))))
     ;;  `(org-special-keyword ((,class (:foreground ,everfrost9))))
     ;;  `(org-table ((,class (:foreground ,everfrost9))))
     ;;  `(org-todo ((,class (:foreground ,everfrost13 :weight bold))))
     ;;  `(org-upcoming-deadline ((,class (:foreground ,everfrost12))))
     ;;  `(org-warning ((,class (:foreground ,everfrost13 :weight bold))))
     ;;  `(font-latex-bold-face ((,class (:inherit bold))))
     ;;  `(font-latex-italic-face ((,class (:slant italic))))
     ;;  `(font-latex-string-face ((,class (:foreground ,everfrost14))))
     ;;  `(font-latex-match-reference-keywords ((,class (:foreground ,everfrost9))))
     ;;  `(font-latex-match-variable-keywords ((,class (:foreground ,everfrost4))))
     ;;  `(ido-only-match ((,class (:foreground ,everfrost8))))
     ;;  `(org-sexp-date ((,class (:foreground ,everfrost7))))
     ;;  `(ido-first-match ((,class (:foreground ,everfrost8 :weight bold))))
     ;;  `(ido-subdir ((,class (:foreground ,everfrost9))))
     ;;  `(org-quote ((,class (:inherit org-block :slant italic))))
     ;;  `(org-verse ((,class (:inherit org-block :slant italic))))
     ;;  `(org-agenda-date-weekend ((,class (:foreground ,everfrost9))))
     ;;  `(org-agenda-date-today ((,class (:foreground ,everfrost8 :weight bold))))
     ;;  `(org-agenda-done ((,class (:foreground ,everfrost14))))
     ;;  `(org-verbatim ((,class (:foreground ,everfrost7))))
     ;;


     ;; > ivy-mode
     `(ivy-current-match ((,class (:inherit region))))
     `(ivy-minibuffer-match-face-1 ((,class (:inherit default))))
     `(ivy-minibuffer-match-face-2 ((,class (:background ,everfrost7 :foreground ,everfrost-fg))))
     `(ivy-minibuffer-match-face-3 ((,class (:background ,everfrost7 :foreground ,everfrost-fg))))
     `(ivy-minibuffer-match-face-4 ((,class (:background ,everfrost7 :foreground ,everfrost-fg))))
     `(ivy-remote ((,class (:foreground ,everfrost-statusline1))))
     `(ivy-posframe ((,class (:background ,everfrost1))))
     `(ivy-posframe-border ((,class (:background ,everfrost1))))
     `(ivy-remote ((,class (:foreground ,everfrost-statusline1))))

     ;; > perspective
     `(persp-selected-face ((,class (:foreground ,everfrost8 :weight bold)))))))

(provide 'everfrost-common)
