(deftheme starlit "The Starlit theme for Emacs, inspired by the Matrix.")

(let ((class '((class color) (min-colors 89)))
      (starlit0 "#062329")
      (starlit1 "#0a3a3e")
      (starlit2 "#2a4043")
      (starlit3 "#304d4e")
      (starlit4 "#bda78c")
      (starlit5 "#c4ad90")
      (starlit6 "#d1b897")
      (starlit7 "#bcd8da")
      (starlit8 "#b5dcef")
      (starlit9 "#a3b5bb")
      (starlit10 "#8299a1")
      (starlit11 "#9b5e56")
      (starlit12 "#d19a66")
      (starlit13 "#c0b84a")
      (starlit14 "#76946a")
      (starlit15 "#7ad0c6")

      (starlit-comment "#2a4043")
      (starlit-annotation "#7ad0c6")
      (starlit-uniform-mode-lines-background "#0a3a3e")
      (starlit-region-highlight-background "#2a4043"))

  (custom-theme-set-faces
   'starlit
   ;; `(default ((,class (:background ,starlit0 :foreground ,starlit6))))
   ;; `(cursor ((,class (:background ,starlit4))))
   ;; `(region ((,class (:background ,starlit2))))
   ;; `(mode-line ((,class (:background ,starlit1 :foreground ,starlit5))))
   ;; `(mode-line-inactive ((,class (:background ,starlit0 :foreground ,starlit3))))
   ;; `(highlight ((,class (:background ,starlit2))))
   ;; `(font-lock-builtin-face ((,class (:foreground ,starlit8))))
   ;; `(font-lock-comment-face ((,class (:foreground ,starlit-comment))))
   ;; `(font-lock-comment-delimiter-face ((,class (:foreground ,starlit-comment))))
   ;; `(font-lock-constant-face ((,class (:foreground ,starlit9))))
   ;; `(font-lock-function-name-face ((,class (:foreground ,starlit9))))
   ;; `(font-lock-function-call-face ((,class (:foreground ,starlit8))))
   ;; `(font-lock-keyword-face ((,class (:foreground ,starlit10))))
   ;; `(font-lock-string-face ((,class (:foreground ,starlit15))))
   ;; `(font-lock-variable-name-face ((,class (:foreground ,starlit6))))
   ;; `(font-lock-variable-use-face ((,class (:foreground ,starlit5))))
   ;; `(font-lock-type-face ((,class (:foreground ,starlit7))))
   ;; `(font-lock-warning-face ((,class (:foreground ,starlit13 :bold t))))


   `(bold ((,class (:weight bold))))
   `(bold-italic ((,class (:weight bold :slant italic))))
   `(default ((,class (:foreground ,starlit4 :background ,starlit0))))
   `(error ((,class (:foreground ,starlit11 :weight bold))))
   `(escape-glyph ((,class (:foreground ,starlit12))))
   `(font-lock-builtin-face ((,class (:foreground ,starlit9))))
   `(font-lock-comment-face ((,class (:foreground ,starlit-comment))))
   `(font-lock-comment-delimiter-face ((,class (:foreground ,starlit-comment))))
   `(font-lock-constant-face ((,class (:foreground ,starlit9))))
   `(font-lock-doc-face ((,class (:foreground ,starlit-comment))))
   `(font-lock-function-name-face ((,class (:foreground ,starlit4))))
   `(font-lock-keyword-face ((,class (:foreground ,starlit9))))
   `(font-lock-negation-char-face ((,class (:foreground ,starlit9))))
   `(font-lock-preprocessor-face ((,class (:foreground ,starlit10 :weight bold))))
   `(font-lock-reference-face ((,class (:foreground ,starlit9))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground ,starlit13))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground ,starlit13))))
   `(font-lock-string-face ((,class (:foreground ,starlit14))))
   `(font-lock-type-face ((,class (:foreground ,starlit7))))
   `(font-lock-variable-name-face ((,class (:foreground ,starlit4))))
   `(font-lock-warning-face ((,class (:foreground ,starlit13))))
   `(italic ((,class (:slant italic))))
   `(shadow ((,class (:foreground ,starlit3))))
   `(underline ((,class (:underline t))))
   `(warning ((,class (:foreground ,starlit13 :weight bold))))


   ;; +--- Syntax ---+
   ;; > C
   `(c-annotation-face ((,class (:foreground ,starlit-annotation))))

   ;; > diff
   `(diff-added ((,class (:foreground ,starlit14))))
   `(diff-changed ((,class (:foreground ,starlit13))))
   `(diff-context ((,class (:inherit default))))
   `(diff-file-header ((,class (:foreground ,starlit8))))
   `(diff-function ((,class (:foreground ,starlit7))))
   `(diff-header ((,class (:foreground ,starlit9 :weight bold))))
   `(diff-hunk-header ((,class (:foreground ,starlit9 :background ,starlit0))))
   `(diff-indicator-added ((,class (:foreground ,starlit14))))
   `(diff-indicator-changed ((,class (:foreground ,starlit13))))
   `(diff-indicator-removed ((,class (:foreground ,starlit11))))
   `(diff-nonexistent ((,class (:foreground ,starlit11))))
   `(diff-refine-added ((,class (:foreground ,starlit14))))
   `(diff-refine-changed ((,class (:foreground ,starlit13))))
   `(diff-refine-removed ((,class (:foreground ,starlit11))))
   `(diff-removed ((,class (:foreground ,starlit11))))


   ;; +--- UI ---+
   `(border ((,class (:foreground ,starlit4))))
   `(buffer-menu-buffer ((,class (:foreground ,starlit4 :weight bold))))
   `(button ((,class (:background ,starlit0 :foreground ,starlit8 :box (:line-width 2 :color ,starlit4 :style sunken-button)))))
   `(completions-annotations ((,class (:foreground ,starlit9))))
   `(completions-common-part ((,class (:foreground ,starlit8 :weight bold))))
   `(completions-first-difference ((,class (:foreground ,starlit11))))
   `(custom-button ((,class (:background ,starlit0 :foreground ,starlit8 :box (:line-width 2 :color ,starlit4 :style sunken-button)))))
   `(custom-button-mouse ((,class (:background ,starlit4 :foreground ,starlit0 :box (:line-width 2 :color ,starlit4 :style sunken-button)))))
   `(custom-button-pressed ((,class (:background ,starlit6 :foreground ,starlit0 :box (:line-width 2 :color ,starlit4 :style sunken-button)))))
   `(custom-button-pressed-unraised ((,class (:background ,starlit4 :foreground ,starlit0 :box (:line-width 2 :color ,starlit4 :style sunken-button)))))
   `(custom-button-unraised ((,class (:background ,starlit0 :foreground ,starlit8 :box (:line-width 2 :color ,starlit4 :style sunken-button)))))
   `(custom-changed ((,class (:foreground ,starlit13))))
   `(custom-comment ((,class (:foreground ,starlit-comment))))
   `(custom-comment-tag ((,class (:foreground ,starlit7))))
   `(custom-documentation ((,class (:foreground ,starlit4))))
   `(custom-group-tag ((,class (:foreground ,starlit8 :weight bold))))
   `(custom-group-tag-1 ((,class (:foreground ,starlit8 :weight bold))))
   `(custom-invalid ((,class (:foreground ,starlit11))))
   `(custom-modified ((,class (:foreground ,starlit13))))
   `(custom-rogue ((,class (:foreground ,starlit12 :background ,starlit2))))
   `(custom-saved ((,class (:foreground ,starlit14))))
   `(custom-set ((,class (:foreground ,starlit8))))
   `(custom-state ((,class (:foreground ,starlit14))))
   `(custom-themed ((,class (:foreground ,starlit8 :background ,starlit2))))
   `(cursor ((,class (:background ,starlit4))))
   `(fringe ((,class (:foreground ,starlit4 :background ,starlit0))))
   `(file-name-shadow ((,class (:inherit shadow))))
   `(header-line ((,class (:foreground ,starlit4 :background ,starlit2))))
   `(help-argument-name ((,class (:foreground ,starlit8))))
   `(highlight ((,class (:foreground ,starlit8 :background ,starlit2))))
   `(hl-line ((,class (:background ,starlit1))))
   `(info-menu-star ((,class (:foreground ,starlit9))))
   `(isearch ((,class (:foreground ,starlit0 :background ,starlit8))))
   `(isearch-fail ((,class (:foreground ,starlit11))))
   `(link ((,class (:underline t))))
   `(link-visited ((,class (:underline t))))
   `(linum ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(linum-relative-current-face ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(match ((,class (:inherit isearch))))
   `(message-cited-text ((,class (:foreground ,starlit4))))
   `(message-header-cc ((,class (:foreground ,starlit9))))
   `(message-header-name ((,class (:foreground ,starlit7))))
   `(message-header-newsgroup ((,class (:foreground ,starlit14))))
   `(message-header-other ((,class (:foreground ,starlit4))))
   `(message-header-subject ((,class (:foreground ,starlit8))))
   `(message-header-to ((,class (:foreground ,starlit9))))
   `(message-header-xheader ((,class (:foreground ,starlit13))))
   `(message-mml ((,class (:foreground ,starlit10))))
   `(message-separator ((,class (:inherit shadow))))
   `(minibuffer-prompt ((,class (:foreground ,starlit8 :weight bold))))
   `(mm-command-output ((,class (:foreground ,starlit8))))
   `(mode-line ((,class (:foreground ,starlit8 :background ,starlit3))))
   `(mode-line-buffer-id ((,class (:weight bold))))
   `(mode-line-highlight ((,class (:inherit highlight))))
   `(mode-line-inactive ((,class (:foreground ,starlit4 :background ,starlit-uniform-mode-lines-background))))
   `(next-error ((,class (:inherit error))))
   `(nobreak-space ((,class (:foreground ,starlit3))))
   `(outline-1 ((,class (:foreground ,starlit8 :weight bold))))
   `(outline-2 ((,class (:inherit outline-1))))
   `(outline-3 ((,class (:inherit outline-1))))
   `(outline-4 ((,class (:inherit outline-1))))
   `(outline-5 ((,class (:inherit outline-1))))
   `(outline-6 ((,class (:inherit outline-1))))
   `(outline-7 ((,class (:inherit outline-1))))
   `(outline-8 ((,class (:inherit outline-1))))
   `(package-description ((,class (:foreground ,starlit4))))
   `(package-help-section-name ((,class (:foreground ,starlit8 :weight bold))))
   `(package-name ((,class (:foreground ,starlit8))))
   `(package-status-available ((,class (:foreground ,starlit7))))
   `(package-status-avail-obso ((,class (:foreground ,starlit7 :slant italic))))
   `(package-status-built-in ((,class (:foreground ,starlit9))))
   `(package-status-dependency ((,class (:foreground ,starlit8 :slant italic))))
   `(package-status-disabled ((,class (:foreground ,starlit3))))
   `(package-status-external ((,class (:foreground ,starlit12 :slant italic))))
   `(package-status-held ((,class (:foreground ,starlit4 :weight bold))))
   `(package-status-new ((,class (:foreground ,starlit14))))
   `(package-status-incompat ((,class (:foreground ,starlit11))))
   `(package-status-installed ((,class (:foreground ,starlit7 :weight bold))))
   `(package-status-unsigned ((,class (:underline ,starlit13))))
   `(query-replace ((,class (:foreground ,starlit8 :background ,starlit2))))
   `(region ((,class (:background ,starlit-region-highlight-background))))
   `(scroll-bar ((,class (:background ,starlit3))))
   `(secondary-selection ((,class (:background ,starlit2))))

   `(vertical-border ((,class (:foreground ,starlit6))))
   `(which-func ((,class (:foreground ,starlit8))))
   `(whitespace-big-indent ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(whitespace-empty ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(whitespace-hspace ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(whitespace-indentation ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(whitespace-line ((,class (:background ,starlit0))))
   `(whitespace-newline ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(whitespace-space ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(whitespace-space-after-tab ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(whitespace-space-before-tab ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(whitespace-tab ((,class (:foreground ,starlit3 :background ,starlit0))))
   `(whitespace-trailing ((,class (:inherit trailing-whitespace))))


   ;;;; Package support

   `(font-latex-bold-face ((,class (:inherit bold))))
   `(font-latex-italic-face ((,class (:inherit italic))))
   `(font-latex-math-face ((,class (:foreground ,starlit8))))
   `(font-latex-sectioning-0-face ((,class (:foreground ,starlit8 :weight bold))))
   `(font-latex-sectioning-1-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-2-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-3-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-4-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-sectioning-5-face ((,class (:inherit font-latex-sectioning-0-face))))
   `(font-latex-script-char-face ((,class (:inherit font-lock-warning-face))))
   `(font-latex-string-face ((,class (:inherit font-lock-string-face))))
   `(font-latex-warning-face ((,class (:inherit font-lock-warning-face))))

   ;; > Elixir
   `(elixir-attribute-face ((,class (:foreground ,starlit-annotation))))
   `(elixir-atom-face ((,class (:foreground ,starlit4 :weight bold))))

   ;; > JavaScript 2
   `(js2-function-call ((,class (:foreground ,starlit8))))
   `(js2-private-function-call ((,class (:foreground ,starlit8))))
   `(js2-jsdoc-html-tag-delimiter ((,class (:foreground ,starlit6))))
   `(js2-jsdoc-html-tag-name ((,class (:foreground ,starlit9))))
   `(js2-external-variable ((,class (:foreground ,starlit4))))
   `(js2-function-param ((,class (:foreground ,starlit4))))
   `(js2-jsdoc-value ((,class (:foreground ,starlit-comment))))
   `(js2-jsdoc-tag ((,class (:foreground ,starlit7))))
   `(js2-jsdoc-type ((,class (:foreground ,starlit7))))
   `(js2-private-member ((,class (:foreground ,starlit4))))
   `(js2-object-property ((,class (:foreground ,starlit4))))
   `(js2-error ((,class (:foreground ,starlit11))))
   `(js2-warning ((,class (:foreground ,starlit13))))
   `(js2-instance-member ((,class (:foreground ,starlit4))))

   ;; > JavaScript 3
   `(js3-error-face ((,class (:foreground ,starlit11))))
   `(js3-external-variable-face ((,class (:foreground ,starlit4))))
   `(js3-function-param-face ((,class (:foreground ,starlit4))))
   `(js3-instance-member-face ((,class (:foreground ,starlit4))))
   `(js3-jsdoc-html-tag-delimiter-face ((,class (:foreground ,starlit6))))
   `(js3-jsdoc-html-tag-name-face ((,class (:foreground ,starlit9))))
   `(js3-jsdoc-tag-face ((,class (:foreground ,starlit9))))
   `(js3-jsdoc-type-face ((,class (:foreground ,starlit7))))
   `(js3-jsdoc-value-face ((,class (:foreground ,starlit4))))
   `(js3-magic-paren-face ((,class (:inherit show-paren-match-face))))
   `(js3-private-function-call-face ((,class (:foreground ,starlit8))))
   `(js3-private-member-face ((,class (:foreground ,starlit4))))
   `(js3-warning-face ((,class (:foreground ,starlit13))))

   ;; > Markdown
   `(markdown-blockquote-face ((,class (:foreground ,starlit-comment))))
   `(markdown-bold-face ((,class (:inherit bold))))
   `(markdown-header-face-1 ((,class (:foreground ,starlit8))))
   `(markdown-header-face-2 ((,class (:foreground ,starlit8))))
   `(markdown-header-face-3 ((,class (:foreground ,starlit8))))
   `(markdown-header-face-4 ((,class (:foreground ,starlit8))))
   `(markdown-header-face-5 ((,class (:foreground ,starlit8))))
   `(markdown-header-face-6 ((,class (:foreground ,starlit8))))
   `(markdown-inline-code-face ((,class (:foreground ,starlit7))))
   `(markdown-italic-face ((,class (:inherit italic))))
   `(markdown-link-face ((,class (:foreground ,starlit8))))
   `(markdown-markup-face ((,class (:foreground ,starlit9))))
   `(markdown-reference-face ((,class (:inherit markdown-link-face))))
   `(markdown-url-face ((,class (:foreground ,starlit4 :underline t))))

   ;; > Company
   `(company-echo-common ((,class (:foreground ,starlit0 :background ,starlit4))))
   `(company-preview ((,class (:foreground ,starlit4 :background ,starlit10))))
   `(company-preview-common ((,class (:foreground ,starlit0 :background ,starlit8))))
   `(company-preview-search ((,class (:foreground ,starlit0 :background ,starlit8))))
   `(company-scrollbar-bg ((,class (:foreground ,starlit1 :background ,starlit1))))
   `(company-scrollbar-fg ((,class (:foreground ,starlit2 :background ,starlit2))))
   `(company-template-field ((,class (:foreground ,starlit0 :background ,starlit7))))
   `(company-tooltip ((,class (:foreground ,starlit4 :background ,starlit2))))
   `(company-tooltip-annotation ((,class (:foreground ,starlit12))))
   `(company-tooltip-annotation-selection ((,class (:foreground ,starlit12 :weight bold))))
   `(company-tooltip-common ((,class (:foreground ,starlit8))))
   `(company-tooltip-common-selection ((,class (:foreground ,starlit8 :background ,starlit3))))
   `(company-tooltip-mouse ((,class (:inherit highlight))))
   `(company-tooltip-selection ((,class (:background ,starlit3 :weight bold))))

   ;; > diff-hl
   `(diff-hl-change ((,class (:background ,starlit13))))
   `(diff-hl-insert ((,class (:background ,starlit14))))
   `(diff-hl-delete ((,class (:background ,starlit11))))

   ;; > Flycheck
   `(flycheck-error ((,class (:underline (:style wave :color ,starlit11)))))
   `(flycheck-fringe-error ((,class (:foreground ,starlit11 :weight bold))))
   `(flycheck-fringe-info ((,class (:foreground ,starlit8 :weight bold))))
   `(flycheck-fringe-warning ((,class (:foreground ,starlit13 :weight bold))))
   `(flycheck-info ((,class (:underline (:style wave :color ,starlit8)))))
   `(flycheck-warning ((,class (:underline (:style wave :color ,starlit13)))))

   ;; > Git Gutter
   `(git-gutter:modified ((,class (:foreground ,starlit13))))
   `(git-gutter:added ((,class (:foreground ,starlit14))))
   `(git-gutter:deleted ((,class (:foreground ,starlit11))))

   ;; > Git Gutter Plus
   `(git-gutter+-modified ((,class (:foreground ,starlit13))))
   `(git-gutter+-added ((,class (:foreground ,starlit14))))
   `(git-gutter+-deleted ((,class (:foreground ,starlit11))))

   ;; > Magit
   `(magit-branch ((,class (:foreground ,starlit7 :weight bold))))
   `(magit-diff-context-highlight ((,class (:background ,starlit2))))
   `(magit-diff-file-header ((,class (:foreground ,starlit8 :box (:color ,starlit8)))))
   `(magit-diffstat-added ((,class (:foreground ,starlit14))))
   `(magit-diffstat-removed ((,class (:foreground ,starlit11))))
   `(magit-hash ((,class (:foreground ,starlit8))))
   `(magit-hunk-heading ((,class (:foreground ,starlit9))))
   `(magit-hunk-heading-highlight ((,class (:foreground ,starlit9 :background ,starlit2))))
   `(magit-item-highlight ((,class (:foreground ,starlit8 :background ,starlit2))))
   `(magit-log-author ((,class (:foreground ,starlit7))))
   `(magit-process-ng ((,class (:foreground ,starlit13 :weight bold))))
   `(magit-process-ok ((,class (:foreground ,starlit14 :weight bold))))
   `(magit-section-heading ((,class (:foreground ,starlit7 :weight bold))))
   `(magit-section-highlight ((,class (:background ,starlit2))))

   ;; > MU4E
   `(mu4e-header-marks-face ((,class (:foreground ,starlit9))))
   `(mu4e-title-face ((,class (:foreground ,starlit8))))
   `(mu4e-header-key-face ((,class (:foreground ,starlit8))))
   `(mu4e-highlight-face ((,class (:highlight))))
   `(mu4e-flagged-face ((,class (:foreground ,starlit13))))
   `(mu4e-unread-face ((,class (:foreground ,starlit13 :weight bold))))
   `(mu4e-link-face ((,class (:underline t))))

   ;; > Powerline
   `(powerline-active1 ((,class (:foreground ,starlit4 :background ,starlit1))))
   `(powerline-active2 ((,class (:foreground ,starlit4 :background ,starlit3))))
   `(powerline-inactive1 ((,class (:background ,starlit2))))
   `(powerline-inactive2 ((,class (:background ,starlit2))))

   ;; > Cider
   `(cider-result-overlay-face ((t (:background unspecified))))

   ;; > Org
   `(org-level-1 ((,class (:foreground ,starlit7 :weight extra-bold))))
   `(org-level-2 ((,class (:foreground ,starlit8 :weight bold))))
   `(org-level-3 ((,class (:foreground ,starlit9 :weight semi-bold))))
   `(org-level-4 ((,class (:foreground ,starlit10 :weight normal))))
   `(org-level-5 ((,class (:inherit org-level-4))))
   `(org-level-6 ((,class (:inherit org-level-4))))
   `(org-level-7 ((,class (:inherit org-level-4))))
   `(org-level-8 ((,class (:inherit org-level-4))))
   `(org-agenda-structure ((,class (:foreground ,starlit9))))
   `(org-agenda-date ((,class (:foreground ,starlit8 :underline nil))))
   `(org-agenda-done ((,class (:foreground ,starlit14))))
   `(org-agenda-dimmed-todo-face ((,class (:background ,starlit13))))
   `(org-block ((,class (:foreground ,starlit4))))
   `(org-block-background ((,class (:background ,starlit0))))
   `(org-block-begin-line ((,class (:foreground ,starlit7))))
   `(org-block-end-line ((,class (:foreground ,starlit7))))
   `(org-checkbox ((,class (:foreground ,starlit9))))
   `(org-checkbox-statistics-done ((,class (:foreground ,starlit14))))
   `(org-checkbox-statistics-todo ((,class (:foreground ,starlit13))))
   `(org-code ((,class (:foreground ,starlit7))))
   `(org-column ((,class (:background ,starlit2))))
   `(org-column-title ((,class (:inherit org-column :weight bold :underline t))))
   `(org-date ((,class (:foreground ,starlit8))))
   `(org-document-info ((,class (:foreground ,starlit4))))
   `(org-document-info-keyword ((,class (:foreground ,starlit3 :weight bold))))
   `(org-document-title ((,class (:foreground ,starlit8 :weight bold))))
   `(org-done ((,class (:foreground ,starlit14 :weight bold))))
   `(org-ellipsis ((,class (:foreground ,starlit3))))
   `(org-footnote ((,class (:foreground ,starlit8))))
   `(org-formula ((,class (:foreground ,starlit9))))
   `(org-hide ((,class (:foreground ,starlit0 :background ,starlit0))))
   `(org-link ((,class (:underline t))))
   `(org-scheduled ((,class (:foreground ,starlit14))))
   `(org-scheduled-previously ((,class (:foreground ,starlit13))))
   `(org-scheduled-today ((,class (:foreground ,starlit8))))
   `(org-special-keyword ((,class (:foreground ,starlit9))))
   `(org-table ((,class (:foreground ,starlit9))))
   `(org-todo ((,class (:foreground ,starlit13 :weight bold))))
   `(org-upcoming-deadline ((,class (:foreground ,starlit12))))
   `(org-warning ((,class (:foreground ,starlit13 :weight bold))))
   `(font-latex-bold-face ((,class (:inherit bold))))
   `(font-latex-italic-face ((,class (:slant italic))))
   `(font-latex-string-face ((,class (:foreground ,starlit14))))
   `(font-latex-match-reference-keywords ((,class (:foreground ,starlit9))))
   `(font-latex-match-variable-keywords ((,class (:foreground ,starlit4))))
   `(ido-only-match ((,class (:foreground ,starlit8))))
   `(org-sexp-date ((,class (:foreground ,starlit7))))
   `(ido-first-match ((,class (:foreground ,starlit8 :weight bold))))
   `(ido-subdir ((,class (:foreground ,starlit9))))
   `(org-quote ((,class (:inherit org-block :slant italic))))
   `(org-verse ((,class (:inherit org-block :slant italic))))
   `(org-agenda-date-weekend ((,class (:foreground ,starlit9))))
   `(org-agenda-date-today ((,class (:foreground ,starlit8 :weight bold))))
   `(org-agenda-done ((,class (:foreground ,starlit14))))
   `(org-verbatim ((,class (:foreground ,starlit7))))

   ;; > ivy-mode
   `(ivy-current-match ((,class (:inherit region))))
   `(ivy-minibuffer-match-face-1 ((,class (:inherit default))))
   `(ivy-minibuffer-match-face-2 ((,class (:background ,starlit7 :foreground ,starlit0))))
   `(ivy-minibuffer-match-face-3 ((,class (:background ,starlit8 :foreground ,starlit0))))
   `(ivy-minibuffer-match-face-4 ((,class (:background ,starlit9 :foreground ,starlit0))))
   `(ivy-remote ((,class (:foreground ,starlit14))))
   `(ivy-posframe ((,class (:background ,starlit1))))
   `(ivy-posframe-border ((,class (:background ,starlit1))))
   `(ivy-remote ((,class (:foreground ,starlit14))))
   ))

(provide-theme 'starlit)
